import { Property, Profile, Subscription, Inquiry } from '@/types/database'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    user_id: 'u1',
    title: '4 Bedroom Detached Duplex',
    description: 'Luxurious 4 bedroom detached duplex in a serene estate with modern finishing. Features include marble flooring, fitted kitchen, central air conditioning, and a private swimming pool.',
    type: 'house',
    listing_type: 'sale',
    price: 85000000,
    location: 'Lekki Phase 1',
    state: 'Lagos',
    city: 'Lagos',
    bedrooms: 4,
    bathrooms: 5,
    area: 350,
    images: [],
    features: ['Swimming Pool', 'Fitted Kitchen', 'Central AC', 'CCTV', 'Smart Home'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    created_at: '2026-03-01T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'u2',
    title: 'Premium 3 Bed Apartment',
    description: 'Stunning 3 bedroom apartment with ocean view, located in the heart of Victoria Island. Fully serviced with 24/7 electricity and security.',
    type: 'apartment',
    listing_type: 'rent',
    price: 5500000,
    location: 'Victoria Island',
    state: 'Lagos',
    city: 'Lagos',
    bedrooms: 3,
    bathrooms: 3,
    area: 180,
    images: [],
    features: ['Ocean View', '24/7 Power', 'Gym', 'Elevator', 'Parking'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: '3',
    user_id: 'u1',
    title: '1000sqm Residential Land',
    description: 'Prime residential land in a well-developed estate in Abuja. All infrastructure in place including tarred roads, drainage, and electricity.',
    type: 'land',
    listing_type: 'sale',
    price: 45000000,
    location: 'Gwarinpa Estate',
    state: 'FCT Abuja',
    city: 'Abuja',
    bedrooms: null,
    bathrooms: null,
    area: 1000,
    images: [],
    features: ['Tarred Roads', 'Drainage', 'Electricity', 'C of O', 'Gated Estate'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    created_at: '2026-03-08T10:00:00Z',
  },
  {
    id: '4',
    user_id: 'u3',
    title: 'Commercial Office Space',
    description: 'Modern open-plan office space in the Ikeja business district. Ideal for tech startups and corporate offices. Floor-to-ceiling windows with city views.',
    type: 'commercial',
    listing_type: 'lease',
    price: 12000000,
    location: 'Ikeja GRA',
    state: 'Lagos',
    city: 'Ikeja',
    bedrooms: null,
    bathrooms: 2,
    area: 250,
    images: [],
    features: ['Open Plan', 'Conference Room', 'Fiber Internet', 'Parking', 'Generator'],
    status: 'approved',
    is_featured: true,
    is_verified: false,
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: '5',
    user_id: 'u2',
    title: '5 Bedroom Mansion with Pool',
    description: 'Exquisite 5 bedroom mansion in the prestigious Banana Island. Features Italian marble, home cinema, wine cellar, and staff quarters.',
    type: 'house',
    listing_type: 'sale',
    price: 650000000,
    location: 'Banana Island',
    state: 'Lagos',
    city: 'Lagos',
    bedrooms: 5,
    bathrooms: 7,
    area: 800,
    images: [],
    features: ['Home Cinema', 'Wine Cellar', 'Staff Quarters', 'Rooftop Terrace', 'Elevator'],
    status: 'approved',
    is_featured: true,
    is_verified: true,
    created_at: '2026-03-12T10:00:00Z',
  },
  {
    id: '6',
    user_id: 'u3',
    title: 'New Development - Green Estate',
    description: 'Off-plan development of 200 units in a gated community. Mix of 2, 3, and 4 bedroom apartments with modern amenities and green spaces.',
    type: 'development',
    listing_type: 'sale',
    price: 35000000,
    location: 'Sangotedo',
    state: 'Lagos',
    city: 'Lagos',
    bedrooms: 3,
    bathrooms: 3,
    area: 150,
    images: [],
    features: ['Gated Community', 'Children Playground', 'Clubhouse', 'Green Areas', 'Solar Power'],
    status: 'pending',
    is_featured: false,
    is_verified: false,
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: '7',
    user_id: 'u1',
    title: '2 Bedroom Flat in Wuse',
    description: 'Affordable 2 bedroom flat in the heart of Wuse II, Abuja. Close to shopping centers, schools, and public transport. Recently renovated.',
    type: 'apartment',
    listing_type: 'rent',
    price: 2500000,
    location: 'Wuse II',
    state: 'FCT Abuja',
    city: 'Abuja',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    images: [],
    features: ['Renovated', 'Water Supply', 'Security', 'Parking'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    created_at: '2026-03-16T10:00:00Z',
  },
  {
    id: '8',
    user_id: 'u2',
    title: 'Warehouse Space - Apapa',
    description: 'Large warehouse space near Apapa port. Suitable for logistics, storage, and light manufacturing. Easy access to major highways.',
    type: 'commercial',
    listing_type: 'lease',
    price: 25000000,
    location: 'Apapa',
    state: 'Lagos',
    city: 'Lagos',
    bedrooms: null,
    bathrooms: 1,
    area: 2000,
    images: [],
    features: ['Loading Bay', 'High Ceiling', 'Security', '24/7 Access', 'Office Space'],
    status: 'approved',
    is_featured: false,
    is_verified: true,
    created_at: '2026-03-18T10:00:00Z',
  },
]

export const MOCK_PROFILES: Profile[] = [
  {
    id: 'u1',
    email: 'agent1@plotmarket.ng',
    full_name: 'Adebayo Okonkwo',
    phone: '+234 801 234 5678',
    role: 'user',
    account_type: 'professional',
    is_verified: true,
    avatar_url: null,
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'u2',
    email: 'agent2@plotmarket.ng',
    full_name: 'Chioma Eze',
    phone: '+234 802 345 6789',
    role: 'user',
    account_type: 'business',
    is_verified: true,
    avatar_url: null,
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'u3',
    email: 'developer@plotmarket.ng',
    full_name: 'Ibrahim Musa',
    phone: '+234 803 456 7890',
    role: 'user',
    account_type: 'starter',
    is_verified: false,
    avatar_url: null,
    created_at: '2026-02-01T10:00:00Z',
  },
]

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 's1',
    user_id: 'u1',
    plan: 'professional',
    amount: 50000,
    start_date: '2026-03-01T00:00:00Z',
    end_date: '2026-04-01T00:00:00Z',
    status: 'active',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 's2',
    user_id: 'u2',
    plan: 'business',
    amount: 100000,
    start_date: '2026-02-15T00:00:00Z',
    end_date: '2026-03-15T00:00:00Z',
    status: 'active',
    created_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 's3',
    user_id: 'u3',
    plan: 'starter',
    amount: 15000,
    start_date: '2026-02-01T00:00:00Z',
    end_date: '2026-03-01T00:00:00Z',
    status: 'expired',
    created_at: '2026-02-01T00:00:00Z',
  },
]

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: 'i1',
    property_id: '1',
    sender_id: 'u3',
    receiver_id: 'u1',
    message: 'I am interested in this property. Is the price negotiable? I would like to schedule a viewing this weekend.',
    status: 'unread',
    created_at: '2026-03-19T10:00:00Z',
  },
  {
    id: 'i2',
    property_id: '2',
    sender_id: 'u1',
    receiver_id: 'u2',
    message: 'Great listing! Can you provide more details about the service charge and available move-in date?',
    status: 'read',
    created_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'i3',
    property_id: '4',
    sender_id: 'u2',
    receiver_id: 'u3',
    message: 'We are looking for office space for our team of 30. Is this space suitable? What about internet connectivity?',
    status: 'replied',
    created_at: '2026-03-17T09:00:00Z',
  },
]
