export const PRICING_PLANS = [
  {
    name: 'Basic',
    price: 0,
    period: 'Free forever',
    listings: 5,
    features: [
      '5 property listings',
      'Basic property details',
      'Email support',
      'Standard visibility',
    ],
    cta: 'Get Started',
    highlighted: false,
  },
  {
    name: 'Starter',
    price: 15000,
    period: '/month',
    listings: 15,
    features: [
      '15 property listings',
      'Featured badge',
      'Priority support',
      'Analytics dashboard',
      'Photo gallery (up to 10)',
    ],
    cta: 'Start Free Trial',
    highlighted: false,
  },
  {
    name: 'Professional',
    price: 50000,
    period: '/month',
    listings: 50,
    features: [
      '50 property listings',
      'Featured & verified badges',
      'Premium support',
      'Advanced analytics',
      'Photo gallery (up to 25)',
      'Virtual tour support',
      'Lead generation tools',
    ],
    cta: 'Start Free Trial',
    highlighted: true,
  },
  {
    name: 'Business',
    price: 100000,
    period: '/month',
    listings: -1,
    features: [
      'Unlimited listings',
      'All Professional features',
      'Dedicated account manager',
      'Custom branding',
      'API access',
      'Bulk upload tools',
      'Team collaboration (5 users)',
    ],
    cta: 'Contact Sales',
    highlighted: false,
  },
  {
    name: 'Enterprise',
    price: 250000,
    period: '/month',
    listings: -1,
    features: [
      'Unlimited listings',
      'All Business features',
      'White-label solution',
      'Custom integrations',
      'SLA guarantee',
      'Unlimited team members',
      'On-premise deployment option',
    ],
    cta: 'Contact Sales',
    highlighted: false,
  },
] as const
