// Listings and sellers served by mock-supabase.mjs and asserted on by the specs.

const base = {
  description: 'Fixture listing for end-to-end tests.',
  type: 'land',
  listing_type: 'sale',
  location: 'Lekki Phase 1',
  city: 'Lekki',
  state: 'Lagos',
  bedrooms: null,
  bathrooms: null,
  area: 600,
  images: [],
  videos: [],
  images_360: [],
  videos_360: [],
  features: [],
  is_featured: false,
  published_at: '2026-09-01T10:00:00Z',
  paused_from: null,
  paused_reason: null,
  estate_name: null,
  pilot_id: null,
  created_at: '2026-09-01T10:00:00Z',
}

export const FIXTURES = {
  real: {
    ...base,
    id: '11111111-1111-4111-8111-111111111111',
    user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    title: 'Two Plots with C of O, Lekki',
    price: 45000000,
    title_document: 'c_of_o',
    status: 'approved',
    // Set on purpose: the old UI turned this into a public "Verified" badge.
    is_verified: true,
    is_demo: false,
  },
  demo: {
    ...base,
    id: '22222222-2222-4222-8222-222222222222',
    user_id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    title: 'Clean 2 Bedroom Flat, Surulere (Demo)',
    type: 'apartment',
    listing_type: 'rent',
    city: 'Surulere',
    price: 1800000,
    title_document: 'deed_of_assignment',
    status: 'approved',
    is_verified: true,
    is_demo: true,
  },
  paused: {
    ...base,
    id: '33333333-3333-4333-8333-333333333333',
    user_id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    title: 'Paused Plot, Ajah',
    price: 20000000,
    title_document: 'excision',
    status: 'paused',
    paused_from: 'approved',
    paused_reason: 'plan_limit',
    is_verified: false,
    is_demo: false,
  },
}

export const PROFILES = [
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',
    email: 'seller@example.com',
    full_name: 'Adaeze Okafor',
    phone: '+2348000000000',
    role: 'user',
    account_type: 'basic',
    user_type: 'agent',
    is_verified: true,
    avatar_url: null,
    company_name: 'Okafor Realty',
    cac_number: null,
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',
    email: 'demo.individual@plotmarket.ng',
    full_name: 'Demo Individual',
    phone: null,
    role: 'user',
    account_type: 'basic',
    user_type: 'individual',
    is_verified: true,
    avatar_url: null,
    company_name: null,
    cac_number: null,
    created_at: '2026-08-01T10:00:00Z',
  },
]
